name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - node-version: 15
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install # using 'install' instead of 'ci' as npm v7 doesn't run the 'prepare' script (see https://github.com/npm/cli/issues/1905)
      name: Install dependencies
    - run: npm test
      name: Run tests
